version: '3.5'

services:
  db:
    container_name: hoya_db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./.env
  api:
    container_name: hoya_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: 'always'
