version: '3.5'

services:
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'
  api:
    container_name: hoya_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - mongo
    volumes:
      - ./:/go/src/hoya-api
